SELECT

  TO_NUMBER(NVAL(SUM(CASE WHEN D.CAPITOL IN (399) AND D.RIND IN ('5000') THEN D.COL1 ELSE  0 END))) ||'-'||  
  TO_NUMBER(TO_NUMBER(SUM(CASE WHEN D.CAPITOL IN (399) AND D.RIND IN ('5100') THEN D.COL1 ELSE  0  END))  
  + TO_NUMBER(NVAL(SUM(CASE WHEN D.CAPITOL IN (401) AND D.RIND IN ('7100','7200','7300','7400','7500') THEN D.COL1 END))))
  AS REZULTAT


FROM
  VW_DATA_ALL D            
   
WHERE
  (D.PERIOADA IN (:PERIOADA)          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (:CAPITOL=:CAPITOL           OR :CAPITOL <> :CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS <>  :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (45)  AND
  D.CAPITOL IN (399,401) 
 

HAVING

