SELECT

  TO_NUMBER(NVAL(SUM(CASE WHEN D.CAPITOL IN (399) AND D.RIND IN ('5100') THEN D.COL1 ELSE  0 END))) ||' < '||  
  TO_NUMBER(SUM(CASE WHEN D.CAPITOL IN (399) AND D.RIND IN ('2000') THEN D.COL1 ELSE  0  END)) 
  

 AS REZULTAT


FROM
  VW_DATA_ALL D            
   
WHERE
  (D.PERIOADA IN (:PERIOADA)          ) AND
  (D.CUIIO=:CUIIO                ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (:CAPITOL=:CAPITOL           OR :CAPITOL <> :CAPITOL) AND
  (:CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS <>  :CAPITOL_VERS) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (45)  AND
  D.CAPITOL IN (399) 
 

HAVING

  TO_NUMBER(NVAL(SUM(CASE WHEN D.CAPITOL IN (399) AND D.RIND IN ('5100') THEN D.COL1 ELSE  0 END)))  <   
  TO_NUMBER(SUM(CASE WHEN D.CAPITOL IN (399) AND D.RIND IN ('2000') THEN D.COL1 ELSE  0  END)) 
